
org_name: Detroit Hacks 2023
org_summary: >
  Detroit Hacks is an event that takes place over two days(Feb 18/19), from 12:30 to 4:30pm each day. It is held at the Novi Public Library in Detroit, and is an opportunity for attendees to attend workshops, gain experience, make connections, and discover more about themselves. The event will feature algorithm-based challenges, various programming levels, and collaboration. It is a great opportunity for those interested in programming and technology to learn and grow their skills.
org_full_description: > 
  DetroitHacks is a non-profit organization that was created by students for students. The president of the organization is Yash Anil. This hackathon is the second one that they have organized. It is a great opportunity for students to learn and grow their skills in technology and programming.

org_general_email_inbox: yashanil@detroithacks.org
org_street_address: 24062 Taft Rd
org_address_suite: Novi High School
org_city: Novi
org_state: MI
org_zip: > 
  48375
org_phone: > 
  (248) 832-2407
#SOCIAL MEDIA
org_twitter_username: N/A
org_facebook_username: N/A
org_instagram_username: AMCC_nhs


fiscal_sponsor: true
fiscal_sponsor_name: Hack Club Bank

is_501c3: true

donorbox_campaign_name: DetroitHacks Hackathon
tinyletter_username: DetroitHacks

#SEARCH ENGINES
#allow your site to be indexed by search engines
publish: true

color_scheme: four


baseurl: "" 
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed


paypal_button_id: 
smartergiving_id: 
