#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: Detroit Hacks 2023
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  At Detroit Hacks, you’ll be able to give & attend workshops from peers, gain experience, make connections, and discover yourself. You’ll meet new people, get help from peers, and support your fellow hackers.
#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: yashanil@detroithacks.org
org_street_address: 24062 Taft Rd
org_address_suite: Novi High School
org_city: Novi
org_state: MI
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  48375
org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  (248) 832-2407
#SOCIAL MEDIA
org_twitter_username: N/A
org_facebook_username: N/A
org_instagram_username: AMCC_nhs

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: true
fiscal_sponsor_name: Hack Club Bank
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
is_501c3: true

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name:
tinyletter_username:

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: true

#COLOR SCHEME
#Select one of the five color schemes (default, one, two, three, or four)
color_scheme: four

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
