
org_name: Detroit Hacks 2023
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  At Detroit Hacks, you’ll be able to give & attend workshops from peers, gain experience, make connections, and discover yourself. You’ll meet new people, get help from peers, and support your fellow hackers.

org_general_email_inbox: yashanil@detroithacks.org
org_street_address: 24062 Taft Rd
org_address_suite: Novi High School
org_city: Novi
org_state: MI
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  48375
org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  (248) 832-2407
#SOCIAL MEDIA
org_twitter_username: N/A
org_facebook_username: N/A
org_instagram_username: AMCC_nhs


fiscal_sponsor: true
fiscal_sponsor_name: Hack Club Bank

is_501c3: true

donorbox_campaign_name:
tinyletter_username:

#SEARCH ENGINES
#allow your site to be indexed by search engines
publish: true

color_scheme: four


baseurl: "" 
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed


paypal_button_id: 
smartergiving_id: 
